flowchart TB
  ED["Eficiência de Desempenho"]
  ED --> Q1E["Q1: Tempos de resposta"]
  ED --> Q2E["Q2: Comportamento sob carga"]
  ED --> Q3E["Q3: Utilização de recursos"]
  ED --> Q4E["Q4: Impacto na aceitabilidade"]
  Q1E --> M1E["M1: Tempo médio & % <=2s"]
  Q2E --> M2E["M2: Throughput e erros"]
  Q3E --> M3E["M3: CPU/Mem médios"]
  Q4E --> M5E["M5: Taxa de abandono por latência"]
